package modelo;
// Generated 2/12/2017 09:08:27 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private Integer idCategoria;
     private String nombreCat;
     private Set<Productos> productoses = new HashSet<Productos>(0);

    public Categoria() {
    }

	
    public Categoria(String nombreCat) {
        this.nombreCat = nombreCat;
    }
    public Categoria(String nombreCat, Set<Productos> productoses) {
       this.nombreCat = nombreCat;
       this.productoses = productoses;
    }
   
    public Integer getIdCategoria() {
        return this.idCategoria;
    }
    
    public void setIdCategoria(Integer idCategoria) {
        this.idCategoria = idCategoria;
    }
    public String getNombreCat() {
        return this.nombreCat;
    }
    
    public void setNombreCat(String nombreCat) {
        this.nombreCat = nombreCat;
    }
    public Set<Productos> getProductoses() {
        return this.productoses;
    }
    
    public void setProductoses(Set<Productos> productoses) {
        this.productoses = productoses;
    }




}


