package modelo;
// Generated 2/12/2017 09:08:27 AM by Hibernate Tools 4.3.1



/**
 * Productos generated by hbm2java
 */
public class Productos  implements java.io.Serializable {


     private Integer idProducto;
     private Categoria categoria;
     private String nombre;
     private String descripcion;
     private int cantidad;
     private double precioUnitario;
     private double precioTotal;

    public Productos() {
    }

    public Productos(Categoria categoria, String nombre, String descripcion, int cantidad, double precioUnitario, double precioTotal) {
       this.categoria = categoria;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.cantidad = cantidad;
       this.precioUnitario = precioUnitario;
       this.precioTotal = precioTotal;
    }
   
    public Integer getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(Integer idProducto) {
        this.idProducto = idProducto;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public double getPrecioUnitario() {
        return this.precioUnitario;
    }
    
    public void setPrecioUnitario(double precioUnitario) {
        this.precioUnitario = precioUnitario;
    }
    public double getPrecioTotal() {
        return this.precioTotal;
    }
    
    public void setPrecioTotal(double precioTotal) {
        this.precioTotal = precioTotal;
    }




}


